#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
for i in sfold ssync; do
    go build -ldflags "-X main.VERSION=$VERSION -linkmode external -extldflags -static" -o bin/$i ./$i/
done
